import path from 'path';
import { fsUtils } from '../utils/fs.js';

export interface CanonicalData {
    instructions: Array<{ name: string; content: string }>;
    agents: Array<{ name: string; content: string }>;
}

export function loadCanonicalData(rootPath: string): CanonicalData {
    const aiPath = path.join(rootPath, 'ai');
    const instructionsDir = path.join(aiPath, 'instructions');
    const agentsDir = path.join(aiPath, 'agents');

    const instructions = fsUtils
        .listFiles(instructionsDir, '.instructions.md')
        .sort((a, b) => a.localeCompare(b))
        .map((filePath) => {
            const base = path.basename(filePath, '.instructions.md');
            return {
                name: base,
                content: fsUtils.readFile(filePath).trim(),
            };
        });

    const agents = fsUtils
        .listFiles(agentsDir, '.agent.md')
        .sort((a, b) => a.localeCompare(b))
        .map((filePath) => {
            const base = path.basename(filePath, '.agent.md');
            return {
                name: base,
                content: fsUtils.readFile(filePath).trim(),
            };
        });

    return { instructions, agents };
}

export function withGeneratedBanner(content: string): string {
    return `<!-- AUTO-GENERATED by syntra. Do not edit manually. Run \`syntra sync\` to update. -->\n\n${content}`;
}

export function instructionTitle(name: string): string {
    return name
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
}
