import path from 'path';
import { fsUtils } from '../utils/fs.js';
import { loadCanonicalData, withGeneratedBanner, instructionTitle } from './common.js';

export interface AdapterResult {
    writtenFiles: string[];
}

function isTaskSkillAliasName(name: string): boolean {
    return name === 'syntra-task' || name === 'task';
}

function buildCopilotFrontmatterDoc(frontmatter: string, body: string): string {
    return `${frontmatter}\n\n<!-- AUTO-GENERATED by syntra. Do not edit manually. Run \`syntra sync\` to update. -->\n\n${body}`;
}

export function syncCopilotAdapter(
    rootPath: string,
    activeTaskDir: string = 'active',
    tasksOnly: boolean = false,
): AdapterResult {
    const data = loadCanonicalData(rootPath, activeTaskDir);

    const outDir = path.join(rootPath, '.github');
    fsUtils.mkdir(outDir);
    const writtenFiles: string[] = [];

    if (!tasksOnly) {
        const agentsDir = path.join(outDir, 'agents');
        fsUtils.mkdir(agentsDir);

        const sections = data.instructions
            .map((item) => `## ${instructionTitle(item.name)}\n\n${item.content}`)
            .join('\n\n');

        const copilotInstructions = withGeneratedBanner(`# Project Instructions\n\n${sections}\n`);
        const instructionsPath = path.join(outDir, 'copilot-instructions.md');
        fsUtils.writeFile(instructionsPath, copilotInstructions);
        writtenFiles.push(instructionsPath);

        for (const agent of data.agents) {
            const content = buildCopilotFrontmatterDoc(
                `---\nname: ${agent.name}\ndescription: ${instructionTitle(agent.name)} agent\n---`,
                `# ${instructionTitle(agent.name)}\n\n${agent.content}\n`,
            );
            const outPath = path.join(agentsDir, `${agent.name}.md`);
            fsUtils.writeFile(outPath, content);
            writtenFiles.push(outPath);
        }
    }

    const promptsDir = path.join(outDir, 'prompts');
    fsUtils.mkdir(promptsDir);

    for (const task of data.tasks) {
        const firstLine = task.content.split('\n')[0] ?? '';
        const description = firstLine.replace(/^#+\s*/, '').trim();
        const content = buildCopilotFrontmatterDoc(
            `---\nmode: 'agent'\ndescription: '${description}'\n---`,
            `${task.content}\n`,
        );
        const outPath = path.join(promptsDir, `${task.name}.prompt.md`);
        fsUtils.writeFile(outPath, content);
        writtenFiles.push(outPath);
    }

    if (!tasksOnly) {
        for (const skill of data.skills) {
            const firstLine = skill.content.split('\n')[0] ?? '';
            const description = firstLine.replace(/^#+\s*/, '').replace(/^---.*/, '').trim() || skill.name;
            const content = buildCopilotFrontmatterDoc(
                `---\nmode: 'agent'\ndescription: '${description}'\n---`,
                `${skill.content}\n`,
            );
            const outPath = path.join(promptsDir, `${skill.name}.prompt.md`);
            fsUtils.writeFile(outPath, content);
            writtenFiles.push(outPath);

            if (isTaskSkillAliasName(skill.name)) {
                const taskAliasPath = path.join(promptsDir, 'task.prompt.md');
                if (taskAliasPath !== outPath) {
                    fsUtils.writeFile(taskAliasPath, content);
                    writtenFiles.push(taskAliasPath);
                }
            }
        }
    }

    return { writtenFiles };
}
